FROM python:3.11.4-bookworm

# set working directory
WORKDIR /app

# install python dependencies
RUN pip install --upgrade pip && pip install poetry

COPY poetry.lock poetry.lock
COPY pyproject.toml pyproject.toml
RUN poetry export -f requirements.txt --output requirements.txt --without-hashes --with dev
RUN python -m  pip install -r requirements.txt

# add app
ADD . .

CMD ["pytest"]
